services:
  api:
    build: .
    container_name: backend_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backend-net

  mongo:
    image: mongo:6
    container_name: backend_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  redis:
    image: redis:7
    container_name: backend_redis
    ports:
      - "6379:6379"
    networks:
      - backend-net

  volumes: 
    mongo-data:
  networks: 
    backend-net:
