# docker-compose.override.yml

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules  # impede conflito entre node_modules local e do container
